#!/usr/bin/env bash

# This script writes the minimal OpenClaw dev-profile config Sage needs for the
# first real wrapper -> OpenClaw integration. It is intentionally conservative:
# loopback only, no chat channels, hooks enabled, and a single default agent.

set -euo pipefail

STATE_DIR="${OPENCLAW_STATE_DIR:-$HOME/.openclaw-dev}"
CONFIG_PATH="${OPENCLAW_CONFIG_PATH:-$STATE_DIR/openclaw.json}"
WORKSPACE_DIR="${SAGE_OC_WORKSPACE_DIR:-$STATE_DIR/workspace}"
GATEWAY_PORT="${SAGE_OC_GATEWAY_PORT:-19001}"
GATEWAY_TOKEN="${SAGE_OC_GATEWAY_TOKEN:-sage-dev-gateway-token}"
HOOK_TOKEN="${SAGE_OC_HOOK_TOKEN:-sage-dev-hook-token}"
PRIMARY_MODEL="${SAGE_OC_PRIMARY_MODEL:-anthropic/claude-sonnet-4-5}"
USER_TIMEZONE="${SAGE_OC_USER_TIMEZONE:-America/New_York}"
CALLBACK_URL="${SAGE_OC_CALLBACK_URL:-}"
CALLBACK_TOKEN="${SAGE_OC_CALLBACK_TOKEN:-}"

mkdir -p "$STATE_DIR" "$WORKSPACE_DIR"

CALLBACK_BLOCK=""
if [ -n "$CALLBACK_URL" ]; then
  # The callback block is optional because the baseline can run without it, but
  # enabling it makes the new hook-completion flow observable during local dev.
  CALLBACK_BLOCK=$(cat <<EOF
    callback: {
      url: "$CALLBACK_URL",
      $( [ -n "$CALLBACK_TOKEN" ] && printf 'token: "%s",\n      ' "$CALLBACK_TOKEN" )
      timeoutMs: 10000,
    },
EOF
)
fi

# We write JSON5 instead of plain JSON because OpenClaw supports comments there,
# which makes the generated file much easier to reason about during local setup.
cat > "$CONFIG_PATH" <<EOF
// Generated by scripts/dev/setup-openclaw-dev-config.sh
//
// This is the minimal Sage baseline for local OpenClaw integration:
// - gateway bound to loopback only
// - dedicated gateway auth token
// - hooks enabled with a separate hook token
// - one default agent workspace
// - no messaging channels configured
// - coding profile with browser/canvas denied for a smaller surface area
{
  gateway: {
    mode: "local",
    bind: "loopback",
    port: $GATEWAY_PORT,
    auth: {
      mode: "token",
      token: "$GATEWAY_TOKEN",
    },
    http: {
      endpoints: {
        chatCompletions: {
          enabled: true,
        },
      },
    },
  },

  agents: {
    defaults: {
      workspace: "$WORKSPACE_DIR",
      skipBootstrap: true,
      userTimezone: "$USER_TIMEZONE",
      model: {
        primary: "$PRIMARY_MODEL",
      },
    },
  },

  tools: {
    profile: "coding",
    deny: ["browser", "canvas"],
  },

  hooks: {
    enabled: true,
    token: "$HOOK_TOKEN",
    path: "/hooks",
$CALLBACK_BLOCK
    defaultSessionKey: "hook:sage",
    allowRequestSessionKey: true,
    allowedSessionKeyPrefixes: ["hook:"],
    allowedAgentIds: ["main"],
  },
}
EOF

chmod 600 "$CONFIG_PATH"

echo "Wrote OpenClaw dev config:"
echo "  $CONFIG_PATH"
echo
echo "Workspace:"
echo "  $WORKSPACE_DIR"
echo
echo "Gateway port:"
echo "  $GATEWAY_PORT"
echo
echo "Hook token:"
echo "  $HOOK_TOKEN"
echo
if [ -n "$CALLBACK_URL" ]; then
  echo "Hook callback URL:"
  echo "  $CALLBACK_URL"
  echo
fi
echo "Note:"
echo "  You still need model credentials in the environment before real task execution will work."
echo "  For the current default model that means ANTHROPIC_API_KEY must be set."
