#!/usr/bin/env bash

# Writes the preconfigured OpenClaw config for a single Sage instance droplet.
# The gateway stays on loopback, chat completions are enabled for the wrapper,
# and bootstrap/onboarding files are skipped so the runtime is ready immediately.

set -euo pipefail

STATE_DIR="${OPENCLAW_STATE_DIR:-/opt/sage/openclaw}"
CONFIG_PATH="${OPENCLAW_CONFIG_PATH:-$STATE_DIR/openclaw.json}"
WORKSPACE_DIR="${SAGE_OC_WORKSPACE_DIR:-$STATE_DIR/workspace}"
GATEWAY_PORT="${SAGE_OC_GATEWAY_PORT:-19001}"
GATEWAY_TOKEN="${SAGE_OC_GATEWAY_TOKEN:-sage-instance-gateway-token}"
HOOK_TOKEN="${SAGE_OC_HOOK_TOKEN:-sage-instance-hook-token}"
PRIMARY_MODEL="${SAGE_OC_PRIMARY_MODEL:-anthropic/claude-sonnet-4-5}"
USER_TIMEZONE="${SAGE_OC_USER_TIMEZONE:-America/New_York}"
CALLBACK_URL="${SAGE_OC_CALLBACK_URL:-}"
CALLBACK_TOKEN="${SAGE_OC_CALLBACK_TOKEN:-}"

mkdir -p "$STATE_DIR" "$WORKSPACE_DIR"

CALLBACK_BLOCK=""
if [ -n "$CALLBACK_URL" ]; then
  CALLBACK_BLOCK=$(cat <<EOF
    callback: {
      url: "$CALLBACK_URL",
      $( [ -n "$CALLBACK_TOKEN" ] && printf 'token: "%s",\n      ' "$CALLBACK_TOKEN" )
      timeoutMs: 10000,
    },
EOF
)
fi

cat > "$CONFIG_PATH" <<EOF
// Generated by scripts/bootstrap/setup-openclaw-instance-config.sh
{
  gateway: {
    mode: "local",
    bind: "loopback",
    port: $GATEWAY_PORT,
    auth: {
      mode: "token",
      token: "$GATEWAY_TOKEN",
    },
    http: {
      endpoints: {
        chatCompletions: {
          enabled: true,
        },
      },
    },
  },

  agents: {
    defaults: {
      workspace: "$WORKSPACE_DIR",
      skipBootstrap: true,
      userTimezone: "$USER_TIMEZONE",
      model: {
        primary: "$PRIMARY_MODEL",
      },
    },
  },

  tools: {
    profile: "coding",
    deny: ["browser", "canvas"],
  },

  hooks: {
    enabled: true,
    token: "$HOOK_TOKEN",
    path: "/hooks",
$CALLBACK_BLOCK
    defaultSessionKey: "hook:sage",
    allowRequestSessionKey: true,
    allowedSessionKeyPrefixes: ["hook:"],
    allowedAgentIds: ["main"],
  },
}
EOF

chmod 600 "$CONFIG_PATH"

echo "Wrote OpenClaw instance config:"
echo "  $CONFIG_PATH"
echo
echo "Workspace:"
echo "  $WORKSPACE_DIR"
echo
echo "Gateway:"
echo "  http://127.0.0.1:$GATEWAY_PORT"
